sonarqube:
  image: sonarqube
  ports:
   - "9000:9000"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://192.168.1.109:5432/sonar
  volumes_from:
   - plugins

plugins:
  image: sonarqube
  volumes:
   - /opt/sonarqube/extensions
   - /opt/sonarqube/lib/bundled-plugins
  command: /bin/true